# Generated by Django 5.1.2 on 2024-10-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(max_length=100)),
                ('apMaterno', models.CharField(max_length=100)),
            ],
        ),
    ]
